[package]
name = "plex_theme_manager"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[[bin]]
name = "ptm"
path = "src/main.rs"